### ISSUE TITLE
1. Understanding the structure of the data

### ISSUE THREAD

**Issue by kakiac** [MultiplAI-UoSuffolk/DNA-Data#4]
- [ ] #5
     - [ ] #15
     - [ ] read introductory material on sequencing of Genome data
     - [ ] summarise key points in #5 
- [ ] Watch tutorials on mRNA data sequencing
     - [ ] Summarise key points in #5 
- [ ] Explore sample FastQ mRNA datasets
    - [ ] download an example dataset for a human from SRA
    - [ ] do some EDA on it and record your notes in #5 
    - [ ] Research other reliable sources for sample data that look like the SRA dataset
    - [ ] save some examples in an organised folder structure in your repository under the name 'datasets'
    - [ ] (optional: if there is time) Explore tools to visualise data quality (e.g. FastQC)
    - [ ] write your notes in #5

Go to the next step #6
