### ISSUE TITLE
2. Build your experiments

### ISSUE THREAD

**Issue by kakiac** [MultiplAI-UoSuffolk/DNA-Data#6]
- [x] #7
    - [ ] Identify a numeric dataset (there are a lot of examples on kaggle.com; any dataset would be fine on this occasion)
    - [ ] choose your clustering algorithm (k-means, hierarchical) suitable for the data
    - [ ]  implement and run clustering on the text data
         - [ ] write python code to apply clustering  algorithms
         - [ ] analyse and interpret your clustering results
         - [ ] use a python notebook (Jupyter) and github codespaces; organise these files in a dedicated folder in your repository
         - [ ] Write your thoughts in #7
- [x] #8
    - [ ] Identify a text dataset (there are a lot of examples on kaggle.com; any dataset would be fine on this occasion for example twitter data, social media data)
    - [ ] choose your clustering algorithm (k-means, hierarchical) suitable for the data
    - [ ]  implement and run clustering on the text data
         - [ ] write python code to apply clustering  algorithms
         - [ ] convert text data to vector data using text vectorising techniques such as TF-IDF, Bag of Words, BERT transformers)
         - [ ] analyse and interpret your clustering results
         - [ ] evaluate the effectiveness of text clustering
         - [ ] compare with the numeric clustering what was different
         - [ ] use a python notebook (Jupyter) and github codespaces; organise these files in a dedicated folder in your repository
         - [ ] write your thoughts in #8
- [x] #9
     - [ ] Identify a mRNA sequencing dataset (it's ok to have the sequencing data of 2 humans to start with)
    - [ ] choose your clustering algorithm (k-means, hierarchical) suitable for the data
    - [ ]  implement and run clustering on the sequenced data
         - [ ] write python code to apply clustering  algorithms
         - [ ] consider converting text data to vector data using text vectorising techniques such as TF-IDF, Bag of Words, BERT transformers)
         - [ ] (optional) consider some ways to improve preprocessing of the sequencing data (such as sequence alignment using BLAST, ways to break down the sequences into units such as k-mer, quality control and cleaning .e.g. applying filters to remove poor-quality data, trimming common adapters and contaminants, implement normalisation and feature selection techniques e.g. TPM, RPKM, select relevant features for clustering such as key features for analysis and statistical methods for selecting features)
         - [ ] analyse and interpret your clustering results
         - [ ] evaluate the effectiveness of text clustering
         - [ ] compare with the numeric clustering what was different
         - [ ] use a python notebook (Jupyter) and github codespaces; organise these files in a dedicated folder in your repository
         - [ ] write your thoughts in #9

Go to next step: 
- [x] #10
